name: tractian_challenge
description: "The tractian mobile challenge"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_injector: ^2.0.4
  dio: ^5.4.3+1
  go_router: ^14.2.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/tractian_logo.png
    - assets/images/company.png
    - assets/images/location.png
    - assets/images/asset.png
    - assets/images/component.png